### ISSUE TITLE
Creation des view et fragement 

### ISSUE THREAD

**Issue by TheNoobProgrammeur** [TheNoobProgrammeur/birudroid#16]
Création des dif view et fragment
Utiliser les maquette de Fidma. 

- [ ] Connexion (fragment)
- [ ] List des bières
   - Gestion des filtres 
- [ ] detaile d'une bière 
- [ ]  ajout d'une bière
- [ ] Menu fav+Profil+Connexion.
   - Gestion des cas : conecter / non conecter 
- [ ] profile

**Comment by acroquelois** [comment]
Rewrite
