### ISSUE TITLE
test/Creation_CI

### ISSUE THREAD

**Issue by TheNoobProgrammeur** [TheNoobProgrammeur/birudroid#4]
:construction_worker: Création d'une CI :construction_worker:

On peut la faire sur Circleci mais je propose de test jenkins pour changer

**Comment by acroquelois** [comment]
Circle CI c'est top, pq se compliquer ?😃

**Comment by TheNoobProgrammeur** [comment]
> 
> 
> Circle CI c'est top, pq se compliquer ?😃

Dac c'etait une proposition
@BBR2394  tu as un avis ?
